// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pyrdxmutmrsiofpxxqhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5cmR4bXV0bXJzaW9mcHh4cWhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0MjcwOTksImV4cCI6MjA1MjAwMzA5OX0.BRyRWsQ6eE5G2h-CFycsaHwPKA2hRZ8uRQk64GmsKp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);